import { useState, type FormEvent } from 'react'
import { Navigate, useLocation, useNavigate } from 'react-router-dom'
import { Eye, EyeOff, KeyRound, Mail } from 'lucide-react'
import { z } from 'zod'
import { AuthShell } from '../components/AuthShell'
import { useAuth } from '../auth/AuthProvider'
import { isSupabaseConfigured, supabase } from '../lib/supabase'

const schema=z.object({email:z.string().email('Escribe un correo válido.'),password:z.string().min(6,'La contraseña debe tener al menos 6 caracteres.')})
export function LoginPage(){const {session}=useAuth();const nav=useNavigate();const location=useLocation();const [mode,setMode]=useState<'login'|'signup'>('login');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [show,setShow]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);if(session)return <Navigate to={new URLSearchParams(location.search).get('next')??'/'} replace/>;
  const submit=async(e:FormEvent)=>{e.preventDefault();setError('');setNotice('');const valid=schema.safeParse({email,password});if(!valid.success){setError(valid.error.issues[0].message);return}if(!isSupabaseConfigured){setError('Falta configurar Supabase. Revisa el archivo .env.');return}setBusy(true);const result=mode==='login'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});setBusy(false);if(result.error){setError('No pudimos iniciar sesión. Revisa tus datos e inténtalo de nuevo.');return}if(mode==='signup'&&!result.data.session){setNotice('Revisa tu correo para confirmar tu cuenta.')}else nav(new URLSearchParams(location.search).get('next')??'/')}
  const magic=async()=>{setError('');const parsed=z.string().email().safeParse(email);if(!parsed.success){setError('Escribe tu correo para enviarte el enlace.');return}setBusy(true);const {error:e}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:window.location.origin}});setBusy(false);if(e)setError('No pudimos enviar el enlace. Inténtalo de nuevo.');else setNotice('Enlace enviado. Revisa tu correo.')}
  return <AuthShell><div className="auth-card"><span className="mobile-logo"><span className="brand-mark">K</span>kinquest</span><div><span className="kicker">{mode==='login'?'Qué bueno verte':'Únete a la aventura'}</span><h2>{mode==='login'?'Bienvenido de vuelta':'Crea tu cuenta'}</h2><p>{mode==='login'?'Tu familia tiene nuevas misiones esperando.':'Empieza hoy a construir hábitos en familia.'}</p></div><form onSubmit={submit} noValidate><label>Correo electrónico<div className="input-wrap"><Mail/><input aria-label="Correo electrónico" type="email" autoComplete="email" placeholder="tu@correo.com" value={email} onChange={e=>setEmail(e.target.value)}/></div></label><label>Contraseña<div className="input-wrap"><KeyRound/><input aria-label="Contraseña" type={show?'text':'password'} autoComplete={mode==='login'?'current-password':'new-password'} placeholder="Mínimo 6 caracteres" value={password} onChange={e=>setPassword(e.target.value)}/><button className="eye" type="button" aria-label="Mostrar contraseña" onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></div></label>{error&&<div className="alert error" role="alert">{error}</div>}{notice&&<div className="alert success" role="status">{notice}</div>}<button className="primary" disabled={busy}>{busy?'Un momento…':mode==='login'?'Entrar a mi familia':'Crear mi cuenta'}</button></form><div className="divider"><span>o</span></div><button className="secondary" onClick={magic} disabled={busy}><Mail/>Enviarme un enlace mágico</button><p className="switch">{mode==='login'?'¿Primera vez aquí?':'¿Ya tienes cuenta?'} <button onClick={()=>{setMode(mode==='login'?'signup':'login');setError('');setNotice('')}}>{mode==='login'?'Crear cuenta':'Iniciar sesión'}</button></p><p className="privacy">Tu información familiar es privada y está protegida.</p></div></AuthShell>}
