import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { Archive, CalendarClock, ClipboardList, Pencil, Plus, RotateCcw, ShieldCheck } from 'lucide-react'
import { supabase } from '../lib/supabase'
import type { ChildProfile, MissionInstance, MissionTemplate, Recurrence } from '../types'

type Draft={title_es:string;title_en:string;description_es:string;description_en:string;icon:string;category:string;xp_value:number;is_required:boolean;recurrence:Recurrence;weekly_days:number[];weekly_flexible:boolean;starts_on:string;assignee_ids:string[]}
const blank=():Draft=>({title_es:'',title_en:'',description_es:'',description_en:'',icon:'⭐',category:'Hogar',xp_value:20,is_required:true,recurrence:'once',weekly_days:[],weekly_flexible:false,starts_on:new Date().toISOString().slice(0,10),assignee_ids:[]})
const dayNames=['Dom','Lun','Mar','Mié','Jue','Vie','Sáb']

export function MissionManager({children}:{familyId:string;children:ChildProfile[]}){
  const [missions,setMissions]=useState<MissionTemplate[]>([]),[instances,setInstances]=useState<MissionInstance[]>([])
  const [draft,setDraft]=useState<Draft>(blank),[editing,setEditing]=useState<string|null>(null),[open,setOpen]=useState(false)
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
  const load=useCallback(async()=>{const [m,i]=await Promise.all([supabase.rpc('list_mission_templates'),supabase.rpc('list_mission_instances',{p_limit:20})]);setMissions((m.data??[]) as MissionTemplate[]);setInstances((i.data??[]) as MissionInstance[])},[])
  useEffect(()=>{void load()},[load])
  const close=()=>{setOpen(false);setEditing(null);setDraft(blank());setError('')}
  const edit=(m:MissionTemplate)=>{setEditing(m.id);setDraft({title_es:m.title_es,title_en:m.title_en,description_es:m.description_es??'',description_en:m.description_en??'',icon:m.icon,category:m.category,xp_value:m.xp_value,is_required:m.is_required,recurrence:m.recurrence,weekly_days:m.weekly_days??[],weekly_flexible:m.weekly_flexible,starts_on:m.starts_on,assignee_ids:m.assignee_ids??[]});setOpen(true)}
  const save=async(e:FormEvent)=>{e.preventDefault();setError('');if(!draft.assignee_ids.length){setError('Selecciona al menos un niño.');return}if(draft.recurrence==='weekly'&&!draft.weekly_flexible&&!draft.weekly_days.length){setError('Selecciona al menos un día o activa la semana flexible.');return}setBusy(true);const args={p_title_es:draft.title_es.trim(),p_title_en:draft.title_en.trim(),p_description_es:draft.description_es.trim()||null,p_description_en:draft.description_en.trim()||null,p_icon:draft.icon.trim(),p_category:draft.category.trim(),p_xp_value:draft.xp_value,p_is_required:draft.is_required,p_recurrence:draft.recurrence,p_weekly_days:draft.weekly_days,p_weekly_flexible:draft.weekly_flexible,p_starts_on:draft.starts_on,p_assignee_ids:draft.assignee_ids};const result=editing?await supabase.rpc('update_mission_template',{p_template_id:editing,...args}):await supabase.rpc('create_mission_template',args);setBusy(false);if(result.error){setError(result.error.message.includes('xp outside')?'El XP está fuera de los límites configurados.':'No se pudo guardar la misión.');return}const wasEditing=Boolean(editing);close();setNotice(wasEditing?'Misión actualizada sin alterar el historial.':'Misión creada y programada.');await load()}
  const archive=async(id:string)=>{setBusy(true);const r=await supabase.rpc('archive_mission_template',{p_template_id:id});setBusy(false);if(r.error)setError('No se pudo archivar la misión.');else{setNotice('Misión archivada; su historial permanece disponible.');await load()}}
  const correct=async(id:string,action:'revert'|'excuse')=>{setBusy(true);const r=await supabase.rpc(action==='revert'?'revert_mission_completion':'excuse_mission_instance',{p_instance_id:id,p_reason:action==='revert'?'Corrección administrativa':'Excepción justificada'});setBusy(false);if(r.error)setError('No se pudo aplicar la corrección.');else{setNotice(action==='revert'?'Finalización revertida y XP retirado.':'Misión justificada sin XP.');await load()}}
  return <section className="missions-card"><div className="section-heading"><div><span className="eyebrow"><ClipboardList/> Misiones</span><h2>Administración de misiones</h2><p>Asigna responsabilidades, XP y recurrencia.</p></div><button className="primary fit" onClick={()=>setOpen(true)} disabled={!children.length}><Plus/>Nueva misión</button></div>{notice&&<div className="alert success mission-notice">{notice}</div>}{error&&!open&&<div className="alert error mission-notice">{error}</div>}
    <div className="mission-grid">{missions.filter(m=>!m.archived_at).map(m=><article className="mission-card" key={m.id}><span className="mission-icon">{m.icon}</span><div><strong>{m.title_es}</strong><small>{m.title_en} · {m.category}</small><span>{m.xp_value} XP · {m.is_required?'Obligatoria':'Opcional'} · {m.recurrence==='once'?'Única':m.recurrence==='daily'?'Diaria':m.weekly_flexible?'Semanal flexible':m.weekly_days.map(d=>dayNames[d]).join(', ')}</span></div><button aria-label={`Editar ${m.title_es}`} onClick={()=>edit(m)}><Pencil/></button><button aria-label={`Archivar ${m.title_es}`} onClick={()=>void archive(m.id)}><Archive/></button></article>)}{missions.every(m=>m.archived_at)&&<p className="muted">Aún no hay misiones activas.</p>}</div>
    <div className="mission-history"><h3><CalendarClock/> Instancias recientes</h3>{instances.length===0?<p className="muted">Aparecerán al programar una misión.</p>:<div className="history-list">{instances.map(i=><article key={i.id}><div><strong>{i.title_es}</strong><small>{i.profile_name} · {i.scheduled_for} · {i.xp_value} XP</small></div><span className={`status ${i.is_excused?'excused':i.status}`}>{i.is_excused?'Justificada':i.status==='completed'?'Completada':'Pendiente'}</span>{i.status==='completed'&&!i.is_excused&&<button title="Revertir" onClick={()=>void correct(i.id,'revert')}><RotateCcw/></button>}{i.status==='pending'&&!i.is_excused&&<button title="Justificar" onClick={()=>void correct(i.id,'excuse')}><ShieldCheck/></button>}</article>)}</div>}</div>
    {open&&<div className="modal-backdrop" onMouseDown={close}><section className="modal mission-modal" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={close}>×</button><h2>{editing?'Editar misión':'Nueva misión'}</h2><p>Los cambios conservan los valores históricos.</p><form onSubmit={save}><div className="form-columns"><label>Título en español<input required minLength={2} maxLength={100} value={draft.title_es} onChange={e=>setDraft({...draft,title_es:e.target.value})}/></label><label>Title in English<input required minLength={2} maxLength={100} value={draft.title_en} onChange={e=>setDraft({...draft,title_en:e.target.value})}/></label><label>Descripción ES<input maxLength={500} value={draft.description_es} onChange={e=>setDraft({...draft,description_es:e.target.value})}/></label><label>Description EN<input maxLength={500} value={draft.description_en} onChange={e=>setDraft({...draft,description_en:e.target.value})}/></label><label>Icono<input required maxLength={20} value={draft.icon} onChange={e=>setDraft({...draft,icon:e.target.value})}/></label><label>Categoría<input required maxLength={50} value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}/></label><label>XP<input type="number" required min={1} max={1000} value={draft.xp_value} onChange={e=>setDraft({...draft,xp_value:Number(e.target.value)})}/></label><label>Inicio<input type="date" required value={draft.starts_on} onChange={e=>setDraft({...draft,starts_on:e.target.value})}/></label><label>Recurrencia<select value={draft.recurrence} onChange={e=>setDraft({...draft,recurrence:e.target.value as Recurrence})}><option value="once">Única</option><option value="daily">Diaria</option><option value="weekly">Semanal</option></select></label><label>Tipo<select value={draft.is_required?'required':'optional'} onChange={e=>setDraft({...draft,is_required:e.target.value==='required'})}><option value="required">Obligatoria</option><option value="optional">Opcional</option></select></label></div>
      {draft.recurrence==='weekly'&&<fieldset><legend>Programación semanal</legend><label className="check-line"><input type="checkbox" checked={draft.weekly_flexible} onChange={e=>setDraft({...draft,weekly_flexible:e.target.checked,weekly_days:e.target.checked?[]:draft.weekly_days})}/> Flexible: una vez antes del domingo</label>{!draft.weekly_flexible&&<div className="day-options">{dayNames.map((n,d)=><button type="button" key={n} className={draft.weekly_days.includes(d)?'selected':''} onClick={()=>setDraft({...draft,weekly_days:draft.weekly_days.includes(d)?draft.weekly_days.filter(x=>x!==d):[...draft.weekly_days,d].sort()})}>{n}</button>)}</div>}</fieldset>}
      <fieldset><legend>Asignar a</legend><label className="check-line"><input type="checkbox" checked={children.length>0&&draft.assignee_ids.length===children.length} onChange={e=>setDraft({...draft,assignee_ids:e.target.checked?children.map(c=>c.id):[]})}/> Todos</label><div className="assignee-options">{children.map(c=><label className="check-line" key={c.id}><input type="checkbox" checked={draft.assignee_ids.includes(c.id)} onChange={e=>setDraft({...draft,assignee_ids:e.target.checked?[...draft.assignee_ids,c.id]:draft.assignee_ids.filter(id=>id!==c.id)})}/>{c.display_name}</label>)}</div></fieldset>{error&&<div className="alert error">{error}</div>}<button className="primary" disabled={busy}>{busy?'Guardando…':'Guardar misión'}</button></form></section></div>}
  </section>
}
