import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { Archive, Check, Gift, Pencil, Plus, X } from 'lucide-react'
import { supabase } from '../lib/supabase'
import type { ChildProfile, Redemption, RedemptionStatus, Reward } from '../types'

type Draft={title_es:string;title_en:string;description_es:string;description_en:string;icon:string;xp_cost:number;is_available:boolean;assignee_ids:string[]}
const blank=():Draft=>({title_es:'',title_en:'',description_es:'',description_en:'',icon:'🎁',xp_cost:100,is_available:true,assignee_ids:[]})
const labels:Record<RedemptionStatus,string>={requested:'Solicitado',approved:'Aprobado',fulfilled:'Entregado',rejected:'Rechazado',cancelled:'Cancelado'}

export function RewardManager({children}:{familyId:string;children:ChildProfile[]}){
  const [rewards,setRewards]=useState<Reward[]>([]),[redemptions,setRedemptions]=useState<Redemption[]>([])
  const [draft,setDraft]=useState<Draft>(blank),[editing,setEditing]=useState<string|null>(null),[open,setOpen]=useState(false)
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
  const load=useCallback(async()=>{const [r,d]=await Promise.all([supabase.rpc('list_rewards_admin'),supabase.rpc('list_redemptions_admin')]);if(r.error||d.error){setError('No se pudieron cargar las recompensas.');return}setRewards((r.data??[]) as Reward[]);setRedemptions((d.data??[]) as Redemption[])},[])
  useEffect(()=>{void load()},[load])
  const close=()=>{setOpen(false);setEditing(null);setDraft(blank());setError('')}
  const edit=(r:Reward)=>{setEditing(r.id);setDraft({title_es:r.title_es,title_en:r.title_en,description_es:r.description_es??'',description_en:r.description_en??'',icon:r.icon,xp_cost:r.xp_cost,is_available:r.is_available,assignee_ids:r.assignee_ids??[]});setOpen(true)}
  const save=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');const {error:e2}=await supabase.rpc('save_reward',{p_reward_id:editing,p_title_es:draft.title_es,p_title_en:draft.title_en,p_description_es:draft.description_es||null,p_description_en:draft.description_en||null,p_icon:draft.icon,p_xp_cost:draft.xp_cost,p_is_available:draft.is_available,p_assignee_ids:draft.assignee_ids});setBusy(false);if(e2){setError('No se pudo guardar la recompensa.');return}close();setNotice(editing?'Recompensa actualizada.':'Recompensa creada.');await load()}
  const archive=async(id:string)=>{setBusy(true);const {error:e}=await supabase.rpc('archive_reward',{p_reward_id:id});setBusy(false);if(e)setError('No se pudo archivar.');else{setNotice('Recompensa archivada; su historial se conserva.');await load()}}
  const transition=async(r:Redemption,status:RedemptionStatus)=>{setBusy(true);setError('');const {error:e}=await supabase.rpc('update_redemption_status',{p_kind:r.kind,p_redemption_id:r.id,p_status:status});setBusy(false);if(e)setError('No se pudo actualizar el canje.');else{setNotice(status==='fulfilled'?(r.kind==='cash'?'Pago confirmado.':'Entrega confirmada.'):status==='rejected'||status==='cancelled'?'Canje cerrado y XP devuelto.':'Canje aprobado.');await load()}}
  return <section className="missions-card rewards-admin"><div className="section-heading"><div><span className="eyebrow"><Gift/> Recompensas</span><h2>Catálogo y canjes</h2><p>Crea premios y gestiona las solicitudes de los niños.</p></div><button className="primary fit" onClick={()=>setOpen(true)}><Plus/>Nueva recompensa</button></div>
    {notice&&<div className="alert success mission-notice">{notice}</div>}{error&&!open&&<div className="alert error mission-notice">{error}</div>}
    <div className="mission-grid reward-grid">{rewards.filter(r=>!r.archived_at).map(r=><article className="mission-card" key={r.id}><span className="mission-icon">{r.icon}</span><div><strong>{r.title_es}</strong><small>{r.title_en}</small><span>{r.xp_cost} XP · {r.is_available?'Disponible':'Pausada'} · {r.assignee_ids.length?`${r.assignee_ids.length} niño(s)`:'Todos'}</span></div><button aria-label={`Editar ${r.title_es}`} onClick={()=>edit(r)}><Pencil/></button><button aria-label={`Archivar ${r.title_es}`} onClick={()=>void archive(r.id)}><Archive/></button></article>)}{rewards.every(r=>r.archived_at)&&<p className="muted">Aún no hay recompensas activas.</p>}</div>
    <div className="mission-history"><h3><Gift/> Solicitudes</h3>{!redemptions.length?<p className="muted">Las solicitudes aparecerán aquí.</p>:<div className="history-list redemption-list">{redemptions.map(r=><article key={`${r.kind}-${r.id}`}><span className="redemption-icon">{r.icon}</span><div><strong>{r.title}</strong><small>{r.profile_name} · {r.xp_amount} XP{r.cad_amount!==null?` · CAD $${Number(r.cad_amount).toFixed(2)}`:''}</small></div><span className={`status ${r.status}`}>{labels[r.status]}</span>{r.status==='requested'&&<><button title="Aprobar" onClick={()=>void transition(r,'approved')}><Check/></button><button title="Rechazar" onClick={()=>void transition(r,'rejected')}><X/></button></>}{r.status==='approved'&&<><button title={r.kind==='cash'?'Confirmar pago':'Confirmar entrega'} onClick={()=>void transition(r,'fulfilled')}><Check/></button><button title="Cancelar" onClick={()=>void transition(r,'cancelled')}><X/></button></>}</article>)}</div>}</div>
    {open&&<div className="modal-backdrop" onMouseDown={close}><section className="modal mission-modal" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={close}>×</button><h2>{editing?'Editar recompensa':'Nueva recompensa'}</h2><p>Sin asignaciones será visible para todos los niños.</p><form onSubmit={save}><div className="form-columns"><label>Título en español<input required minLength={2} maxLength={100} value={draft.title_es} onChange={e=>setDraft({...draft,title_es:e.target.value})}/></label><label>Title in English<input required minLength={2} maxLength={100} value={draft.title_en} onChange={e=>setDraft({...draft,title_en:e.target.value})}/></label><label>Descripción ES<input maxLength={500} value={draft.description_es} onChange={e=>setDraft({...draft,description_es:e.target.value})}/></label><label>Description EN<input maxLength={500} value={draft.description_en} onChange={e=>setDraft({...draft,description_en:e.target.value})}/></label><label>Icono<input required maxLength={20} value={draft.icon} onChange={e=>setDraft({...draft,icon:e.target.value})}/></label><label>Costo en XP<input required type="number" min={1} value={draft.xp_cost} onChange={e=>setDraft({...draft,xp_cost:Number(e.target.value)})}/></label></div><label className="check-line"><input type="checkbox" checked={draft.is_available} onChange={e=>setDraft({...draft,is_available:e.target.checked})}/> Disponible para solicitar</label><fieldset><legend>Limitar a niños (opcional)</legend><div className="assignee-options">{children.map(c=><label className="check-line" key={c.id}><input type="checkbox" checked={draft.assignee_ids.includes(c.id)} onChange={e=>setDraft({...draft,assignee_ids:e.target.checked?[...draft.assignee_ids,c.id]:draft.assignee_ids.filter(id=>id!==c.id)})}/>{c.display_name}</label>)}</div></fieldset>{error&&<div className="alert error">{error}</div>}<button className="primary" disabled={busy}>{busy?'Guardando…':'Guardar recompensa'}</button></form></section></div>}
  </section>
}
